name : ci

on:
  pull_request:
    paths:
      - "backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        working-directory: ./backend
        run: chmod +x ./gradlew

      - name: Test
        working-directory: ./backend
        run: ./gradlew koverXmlReport

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/backend/build/reports/kover/report.xml
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 40
          min-coverage-changed-files: 40
          coverage-counter-type: LINE